version: '3.8'

services:
  client:
    container_name: prodClient
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run prod
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet
networks:
  webnet:
