version: '3.8'

services:
  quasar-ssr:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Монтируем код внутрь контейнера
    env_file:
      - .env
    restart: always
