import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1740509177262 implements MigrationInterface {
    name = 'Auto1740509177262'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "auth-confirm" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "type" character varying NOT NULL, "userId" integer, CONSTRAINT "PK_0302013ded81b86ef26554ef475" PRIMARY KEY ("id", "uuid"))`);
        await queryRunner.query(`CREATE TABLE "pages-components" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "order" integer NOT NULL DEFAULT '0', "name" character varying(1024) NOT NULL, "content" json, "pagesId" integer, CONSTRAINT "PK_f974e55e02452b8cee3b03fdafa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings_menu" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "title" character varying(512) NOT NULL, "slug" character varying(512), CONSTRAINT "PK_fd3bebc7d7b006af8b6c75842d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings_menu_item" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "title" character varying(512) NOT NULL, "hash" character varying(512), "order" integer NOT NULL DEFAULT '0', "mpath" character varying DEFAULT '', "menuId" integer, "pagesId" integer, "parentId" integer, CONSTRAINT "PK_8656070d632a256909b4b23d456" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_params_field_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_params_field_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_params_field_value_lang_enum" NOT NULL, "pagesParamsFieldId" integer, CONSTRAINT "PK_27ec26e5cb664f94dc1f035d45d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_params_field" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "paramsId" integer, "recordId" integer, CONSTRAINT "PK_671a6993b20eff8aa4b6d0d2724" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_params" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, "type" character varying NOT NULL DEFAULT 'text', "isFilter" boolean NOT NULL DEFAULT false, "pagesId" integer, CONSTRAINT "PK_61558e5b9f6c57acf151ab7bd2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_seo_params_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TYPE "public"."pages_seo_params_fieldtype_enum" AS ENUM('title', 'description', 'keywords')`);
        await queryRunner.query(`CREATE TABLE "pages_seo_params" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "content" character varying(2048) NOT NULL DEFAULT '', "lang" "public"."pages_seo_params_lang_enum" NOT NULL, "fieldType" "public"."pages_seo_params_fieldtype_enum" NOT NULL, "pagesSeoId" integer, CONSTRAINT "PK_e8dd1b4fdafa610adcca5bf84c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_seo" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, CONSTRAINT "PK_3c9a1e22921f011629a98a50bcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_iblock_fields_label_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_fields_label" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_iblock_fields_label_lang_enum" NOT NULL, "fieldId" integer, CONSTRAINT "PK_550bab3bdf9ebb94a1ff787b214" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_iblock_section_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_section_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_iblock_section_value_lang_enum" NOT NULL, "sectionId" integer, CONSTRAINT "PK_0a2f2d4c7086efb44458284e778" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_section" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "iblockId" integer, CONSTRAINT "PK_1ec64f9522097554d372e30015d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_records" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "sort" integer DEFAULT '0', "iblockId" integer, CONSTRAINT "PK_a172545fb26a8290f02c3b9e064" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_iblock_records_field_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_records_field_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_iblock_records_field_value_lang_enum" NOT NULL, "recordFieldId" integer, CONSTRAINT "PK_1e8099f640b25eb69875b5cac34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_records_field" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "recordId" integer, "fieldId" integer, CONSTRAINT "PK_933cc9b1b8634b10bb82cd0b2df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_iblock_fields_type_enum" AS ENUM('text', 'array', 'image', 'editor')`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_fields" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, "type" "public"."pages_iblock_fields_type_enum" NOT NULL, "iblockId" integer, CONSTRAINT "PK_f21023738aad31b8f43845d3d35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_iblock" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, "attributes" json, "pageId" integer, CONSTRAINT "PK_5510dbca6afcd98fee2fad2eb7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_sections_title_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_sections_title_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_sections_title_value_lang_enum" NOT NULL, "sectionId" integer, CONSTRAINT "PK_a2baa08eeef049e79971b31a9a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_sections_description_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "pages_sections_description_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."pages_sections_description_value_lang_enum" NOT NULL, "sectionId" integer, CONSTRAINT "PK_34c23cca366c9064d2a33b1292c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages_sections" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "pagesId" integer, CONSTRAINT "PK_e5e45301d05b0d552ff5990d0a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "description" character varying, "slug" character varying, "type" character varying NOT NULL DEFAULT 'Landing', "pagePath" json, "seoId" integer, CONSTRAINT "REL_a5f09c91bfe53121be839fd575" UNIQUE ("seoId"), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."records_title_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "records_title_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."records_title_value_lang_enum" NOT NULL, "recordTitleId" integer, CONSTRAINT "PK_eb84deec53569be83341a56b7bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "records_title" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, CONSTRAINT "PK_29a71191545007258f8b186f4a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."records_seo_params_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TYPE "public"."records_seo_params_fieldtype_enum" AS ENUM('title', 'description', 'keywords')`);
        await queryRunner.query(`CREATE TABLE "records_seo_params" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "content" character varying(2048) NOT NULL DEFAULT '', "lang" "public"."records_seo_params_lang_enum" NOT NULL, "fieldType" "public"."records_seo_params_fieldtype_enum" NOT NULL, "recordSeoId" integer, CONSTRAINT "PK_bacdca37f5b71b05ac80ab3ca12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "records_seo" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, CONSTRAINT "PK_8fdbfa9dec79b858c082393ffcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."records_description_value_lang_enum" AS ENUM('ru-RU', 'en-US', 'zh-CN')`);
        await queryRunner.query(`CREATE TABLE "records_description_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "lang" "public"."records_description_value_lang_enum" NOT NULL, "recordDescriptionId" integer, CONSTRAINT "PK_ff78d512547f3469833b269c97c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "records_description" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, CONSTRAINT "PK_10d93e0da254803a07c18aa19dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "records" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "countView" integer NOT NULL DEFAULT '0', "titleId" integer, "descriptionId" integer, "pagesId" integer, "authorId" integer, "seoId" integer, CONSTRAINT "REL_e818af141fb00405011ff5ee1e" UNIQUE ("titleId"), CONSTRAINT "REL_0b294cd175a264787d609315ba" UNIQUE ("descriptionId"), CONSTRAINT "REL_67fe1339b944fb02568867554b" UNIQUE ("seoId"), CONSTRAINT "PK_188149422ee2454660abf1d5ee5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pages-comments" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "content" character varying, "status" character varying NOT NULL DEFAULT 'verify', "level" integer NOT NULL, "recordsId" integer, "userId" integer, "parentId" integer, CONSTRAINT "PK_bb7aa821e7839f43b46d83070b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT false, "lastName" character varying(1024) NOT NULL, "firstName" character varying(1024) NOT NULL, "middleName" character varying(1024), "email" character varying(1024) NOT NULL, "password" character varying(2048) NOT NULL, "role" character varying NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "title" character varying(1024) NOT NULL, "description" character varying(1024), "vk" character varying(1024), "facebook" character varying(1024), "viber" character varying(1024), "whatsapp" character varying(1024), "telegram" character varying(1024), "discord" character varying(1024), "linkedIn" character varying(1024), "instagram" character varying(1024), "phone" character varying(1024), "email" character varying(1024), "urlBitrix" character varying DEFAULT '', "amoClientId" character varying DEFAULT '', "amoClientSecret" character varying DEFAULT '', "amoDomain" character varying DEFAULT '', "amoBearer" character varying DEFAULT '', CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings-contacts" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "content" character varying(1024), "description" character varying(1024), "isPhone" boolean NOT NULL DEFAULT false, "emailId" integer, "phoneId" integer, CONSTRAINT "PK_bd85d9cf5847a5d982b9d933d86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reference_book_instances" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "referenceBookId" integer, CONSTRAINT "PK_c0835b5c84fd07195adac5b8abd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reference_book_instances_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying, "valueJson" json, "instanceId" integer, "attributeId" integer, CONSTRAINT "PK_a60b6dbd7dc285610721c8e0d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reference_book_attributes" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, "type" character varying NOT NULL DEFAULT 'text', "referenceBookId" integer, CONSTRAINT "PK_64a1d13a5cffe2bd3585a05b037" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reference_book" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, CONSTRAINT "PK_18e7d4038ac6f83249ba35baf63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "callback_instances" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "callbackId" integer, CONSTRAINT "PK_b6ffbe12380b59fa96b2b2b8843" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "callback_instances_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "value" character varying DEFAULT '', "instanceId" integer, "fieldId" integer, CONSTRAINT "PK_87e7dd5c2a589525181b6162dda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "callback_field" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "type" character varying NOT NULL DEFAULT 'string', "attribute" character varying NOT NULL DEFAULT 'title', "isRequred" boolean NOT NULL DEFAULT false, "callbackId" integer, CONSTRAINT "PK_1b338762b5bb2fb54b5efc2603e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "callback" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "name" character varying(1024) NOT NULL, "slug" character varying(1024) NOT NULL, "syncBitrix" boolean NOT NULL DEFAULT false, "syncAmo" boolean NOT NULL DEFAULT false, "email" character varying(1024), CONSTRAINT "PK_3120f6061b840c2605321da3947" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "amo_custom_fields" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "amoID" integer, "attribute" character varying NOT NULL DEFAULT 'title', CONSTRAINT "PK_715cf8ed3ea681a677ab5c7b82c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "library_files" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "updatedAt" TIMESTAMP NOT NULL DEFAULT '"2025-02-25T18:46:18.553Z"', "deletedAt" TIMESTAMP, "path" character varying, "type" character varying NOT NULL DEFAULT 'file', "name" character varying, "filename" character varying, "size" integer, "isSystem" boolean NOT NULL DEFAULT false, "parentId" integer, CONSTRAINT "PK_23c28486f5385fca7a0b557f910" PRIMARY KEY ("id")); COMMENT ON COLUMN "library_files"."path" IS 'Путь к файлу'; COMMENT ON COLUMN "library_files"."type" IS 'Тип файла'; COMMENT ON COLUMN "library_files"."name" IS 'Название файла или директории'; COMMENT ON COLUMN "library_files"."filename" IS 'Название в облаке'; COMMENT ON COLUMN "library_files"."size" IS 'Размер файла'; COMMENT ON COLUMN "library_files"."isSystem" IS 'Системная директория'`);
        await queryRunner.query(`CREATE TABLE "pages_iblock_records_sections_pages_iblock_section" ("pagesIblockRecordsId" integer NOT NULL, "pagesIblockSectionId" integer NOT NULL, CONSTRAINT "PK_906e8c5fd253990a7311a2e39ed" PRIMARY KEY ("pagesIblockRecordsId", "pagesIblockSectionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00c890d8787b39924577c17693" ON "pages_iblock_records_sections_pages_iblock_section" ("pagesIblockRecordsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_03146727e4ec451f4d6569fe17" ON "pages_iblock_records_sections_pages_iblock_section" ("pagesIblockSectionId") `);
        await queryRunner.query(`CREATE TABLE "records_sections_pages_sections" ("recordsId" integer NOT NULL, "pagesSectionsId" integer NOT NULL, CONSTRAINT "PK_f021a3b1c8a7b996698fb04b0bb" PRIMARY KEY ("recordsId", "pagesSectionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b16cf6a8d2cd77c4e5c900e78" ON "records_sections_pages_sections" ("recordsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e60081aaa73c87282096ff7d02" ON "records_sections_pages_sections" ("pagesSectionsId") `);
        await queryRunner.query(`CREATE TABLE "users_comments_like" ("pagesCommentsId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_1bcb4b63e735ea92636c42d68ad" PRIMARY KEY ("pagesCommentsId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b3e0c5f255dc2934f4e08bf11" ON "users_comments_like" ("pagesCommentsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_146347ac8247c1f560194c0046" ON "users_comments_like" ("userId") `);
        await queryRunner.query(`ALTER TABLE "auth-confirm" ADD CONSTRAINT "FK_c1b9f162da24fa4cb098170b8cc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages-components" ADD CONSTRAINT "FK_e2cecde5138675709548651bdc3" FOREIGN KEY ("pagesId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" ADD CONSTRAINT "FK_bc7149e0b6c462ea0a78e25fcde" FOREIGN KEY ("menuId") REFERENCES "settings_menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" ADD CONSTRAINT "FK_d2eb1a13366bb09677b8f8b9a94" FOREIGN KEY ("pagesId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" ADD CONSTRAINT "FK_08220f7645a0e6e5e73ebf825bb" FOREIGN KEY ("parentId") REFERENCES "settings_menu_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_params_field_value" ADD CONSTRAINT "FK_17cd61295a0eeaa3fd030861652" FOREIGN KEY ("pagesParamsFieldId") REFERENCES "pages_params_field"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_params_field" ADD CONSTRAINT "FK_1dad757c0e0f6e8e8c24c487058" FOREIGN KEY ("paramsId") REFERENCES "pages_params"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_params_field" ADD CONSTRAINT "FK_4b3b4870b43caf984a5ff22139a" FOREIGN KEY ("recordId") REFERENCES "records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_params" ADD CONSTRAINT "FK_d1470054f3bad349990679c249b" FOREIGN KEY ("pagesId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_seo_params" ADD CONSTRAINT "FK_d6d341a3d07869e14b4c55853a7" FOREIGN KEY ("pagesSeoId") REFERENCES "pages_seo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_fields_label" ADD CONSTRAINT "FK_a979481317c46275274d317e314" FOREIGN KEY ("fieldId") REFERENCES "pages_iblock_fields"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_section_value" ADD CONSTRAINT "FK_59bb77f411f7c3be37ff26667ed" FOREIGN KEY ("sectionId") REFERENCES "pages_iblock_section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_section" ADD CONSTRAINT "FK_dacc6f7003e51056134cb17b68f" FOREIGN KEY ("iblockId") REFERENCES "pages_iblock"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records" ADD CONSTRAINT "FK_ac05c90b7748d12564a17aa946f" FOREIGN KEY ("iblockId") REFERENCES "pages_iblock"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field_value" ADD CONSTRAINT "FK_4f1a7deb7b7f84a540dfc7e6019" FOREIGN KEY ("recordFieldId") REFERENCES "pages_iblock_records_field"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field" ADD CONSTRAINT "FK_e5dc88e85ea29c8192c9ea6fb7e" FOREIGN KEY ("recordId") REFERENCES "pages_iblock_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field" ADD CONSTRAINT "FK_f929fe9c470a6478598aa51e2a1" FOREIGN KEY ("fieldId") REFERENCES "pages_iblock_fields"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_fields" ADD CONSTRAINT "FK_286592815ea93247dec6e525026" FOREIGN KEY ("iblockId") REFERENCES "pages_iblock"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock" ADD CONSTRAINT "FK_9ff9ce259ae047c9e72ca14b154" FOREIGN KEY ("pageId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_sections_title_value" ADD CONSTRAINT "FK_f528e26b260dd3549b3d12d351b" FOREIGN KEY ("sectionId") REFERENCES "pages_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_sections_description_value" ADD CONSTRAINT "FK_1a83673d9038871d40167cee5eb" FOREIGN KEY ("sectionId") REFERENCES "pages_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_sections" ADD CONSTRAINT "FK_e1c5792780a5472be4825966d94" FOREIGN KEY ("pagesId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_a5f09c91bfe53121be839fd5754" FOREIGN KEY ("seoId") REFERENCES "pages_seo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records_title_value" ADD CONSTRAINT "FK_846313cd8a383414fbbc7a972fc" FOREIGN KEY ("recordTitleId") REFERENCES "records_title"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records_seo_params" ADD CONSTRAINT "FK_0e55c273815033b03161025773c" FOREIGN KEY ("recordSeoId") REFERENCES "records_seo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records_description_value" ADD CONSTRAINT "FK_233e9ab819ebd34d6023136a49f" FOREIGN KEY ("recordDescriptionId") REFERENCES "records_description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records" ADD CONSTRAINT "FK_e818af141fb00405011ff5ee1ef" FOREIGN KEY ("titleId") REFERENCES "records_title"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records" ADD CONSTRAINT "FK_0b294cd175a264787d609315ba5" FOREIGN KEY ("descriptionId") REFERENCES "records_description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records" ADD CONSTRAINT "FK_0cec391de59aa39be0eff0c4754" FOREIGN KEY ("pagesId") REFERENCES "pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records" ADD CONSTRAINT "FK_447389c0c9dcc190dc22a379e81" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records" ADD CONSTRAINT "FK_67fe1339b944fb02568867554bf" FOREIGN KEY ("seoId") REFERENCES "records_seo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages-comments" ADD CONSTRAINT "FK_48b1feb57fba8d9913b26cc9ea1" FOREIGN KEY ("recordsId") REFERENCES "records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages-comments" ADD CONSTRAINT "FK_f18adbc5cfd113a69abd01f731b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages-comments" ADD CONSTRAINT "FK_44cba60a41f892b3d3af00d335c" FOREIGN KEY ("parentId") REFERENCES "pages-comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings-contacts" ADD CONSTRAINT "FK_58e7cd4fb92406dd078459ef407" FOREIGN KEY ("emailId") REFERENCES "settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings-contacts" ADD CONSTRAINT "FK_73972c5106d5e1b9911c9cd67e3" FOREIGN KEY ("phoneId") REFERENCES "settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances" ADD CONSTRAINT "FK_990cdbc304e6a407b3a4ebb9c95" FOREIGN KEY ("referenceBookId") REFERENCES "reference_book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances_value" ADD CONSTRAINT "FK_f7cae818770360f5ba9232c030f" FOREIGN KEY ("instanceId") REFERENCES "reference_book_instances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances_value" ADD CONSTRAINT "FK_57d597dd4836afdc5f298c59f81" FOREIGN KEY ("attributeId") REFERENCES "reference_book_attributes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_book_attributes" ADD CONSTRAINT "FK_07a2b8f8cc0b98e673bdf2b4744" FOREIGN KEY ("referenceBookId") REFERENCES "reference_book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "callback_instances" ADD CONSTRAINT "FK_36e626ed1c64f96ce117ae4402f" FOREIGN KEY ("callbackId") REFERENCES "callback"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "callback_instances_value" ADD CONSTRAINT "FK_d9da9581c93d2f601fd5e0945a6" FOREIGN KEY ("instanceId") REFERENCES "callback_instances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "callback_instances_value" ADD CONSTRAINT "FK_f3d100f2b66fffb5d021ce77232" FOREIGN KEY ("fieldId") REFERENCES "callback_field"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "callback_field" ADD CONSTRAINT "FK_ce5cebd05d199adf25f0a183db8" FOREIGN KEY ("callbackId") REFERENCES "callback"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library_files" ADD CONSTRAINT "FK_bd27818610bfceabf7bbcdf494c" FOREIGN KEY ("parentId") REFERENCES "library_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_sections_pages_iblock_section" ADD CONSTRAINT "FK_00c890d8787b39924577c17693b" FOREIGN KEY ("pagesIblockRecordsId") REFERENCES "pages_iblock_records"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_sections_pages_iblock_section" ADD CONSTRAINT "FK_03146727e4ec451f4d6569fe178" FOREIGN KEY ("pagesIblockSectionId") REFERENCES "pages_iblock_section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "records_sections_pages_sections" ADD CONSTRAINT "FK_8b16cf6a8d2cd77c4e5c900e787" FOREIGN KEY ("recordsId") REFERENCES "records"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "records_sections_pages_sections" ADD CONSTRAINT "FK_e60081aaa73c87282096ff7d027" FOREIGN KEY ("pagesSectionsId") REFERENCES "pages_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_comments_like" ADD CONSTRAINT "FK_6b3e0c5f255dc2934f4e08bf110" FOREIGN KEY ("pagesCommentsId") REFERENCES "pages-comments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_comments_like" ADD CONSTRAINT "FK_146347ac8247c1f560194c00465" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_comments_like" DROP CONSTRAINT "FK_146347ac8247c1f560194c00465"`);
        await queryRunner.query(`ALTER TABLE "users_comments_like" DROP CONSTRAINT "FK_6b3e0c5f255dc2934f4e08bf110"`);
        await queryRunner.query(`ALTER TABLE "records_sections_pages_sections" DROP CONSTRAINT "FK_e60081aaa73c87282096ff7d027"`);
        await queryRunner.query(`ALTER TABLE "records_sections_pages_sections" DROP CONSTRAINT "FK_8b16cf6a8d2cd77c4e5c900e787"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_sections_pages_iblock_section" DROP CONSTRAINT "FK_03146727e4ec451f4d6569fe178"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_sections_pages_iblock_section" DROP CONSTRAINT "FK_00c890d8787b39924577c17693b"`);
        await queryRunner.query(`ALTER TABLE "library_files" DROP CONSTRAINT "FK_bd27818610bfceabf7bbcdf494c"`);
        await queryRunner.query(`ALTER TABLE "callback_field" DROP CONSTRAINT "FK_ce5cebd05d199adf25f0a183db8"`);
        await queryRunner.query(`ALTER TABLE "callback_instances_value" DROP CONSTRAINT "FK_f3d100f2b66fffb5d021ce77232"`);
        await queryRunner.query(`ALTER TABLE "callback_instances_value" DROP CONSTRAINT "FK_d9da9581c93d2f601fd5e0945a6"`);
        await queryRunner.query(`ALTER TABLE "callback_instances" DROP CONSTRAINT "FK_36e626ed1c64f96ce117ae4402f"`);
        await queryRunner.query(`ALTER TABLE "reference_book_attributes" DROP CONSTRAINT "FK_07a2b8f8cc0b98e673bdf2b4744"`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances_value" DROP CONSTRAINT "FK_57d597dd4836afdc5f298c59f81"`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances_value" DROP CONSTRAINT "FK_f7cae818770360f5ba9232c030f"`);
        await queryRunner.query(`ALTER TABLE "reference_book_instances" DROP CONSTRAINT "FK_990cdbc304e6a407b3a4ebb9c95"`);
        await queryRunner.query(`ALTER TABLE "settings-contacts" DROP CONSTRAINT "FK_73972c5106d5e1b9911c9cd67e3"`);
        await queryRunner.query(`ALTER TABLE "settings-contacts" DROP CONSTRAINT "FK_58e7cd4fb92406dd078459ef407"`);
        await queryRunner.query(`ALTER TABLE "pages-comments" DROP CONSTRAINT "FK_44cba60a41f892b3d3af00d335c"`);
        await queryRunner.query(`ALTER TABLE "pages-comments" DROP CONSTRAINT "FK_f18adbc5cfd113a69abd01f731b"`);
        await queryRunner.query(`ALTER TABLE "pages-comments" DROP CONSTRAINT "FK_48b1feb57fba8d9913b26cc9ea1"`);
        await queryRunner.query(`ALTER TABLE "records" DROP CONSTRAINT "FK_67fe1339b944fb02568867554bf"`);
        await queryRunner.query(`ALTER TABLE "records" DROP CONSTRAINT "FK_447389c0c9dcc190dc22a379e81"`);
        await queryRunner.query(`ALTER TABLE "records" DROP CONSTRAINT "FK_0cec391de59aa39be0eff0c4754"`);
        await queryRunner.query(`ALTER TABLE "records" DROP CONSTRAINT "FK_0b294cd175a264787d609315ba5"`);
        await queryRunner.query(`ALTER TABLE "records" DROP CONSTRAINT "FK_e818af141fb00405011ff5ee1ef"`);
        await queryRunner.query(`ALTER TABLE "records_description_value" DROP CONSTRAINT "FK_233e9ab819ebd34d6023136a49f"`);
        await queryRunner.query(`ALTER TABLE "records_seo_params" DROP CONSTRAINT "FK_0e55c273815033b03161025773c"`);
        await queryRunner.query(`ALTER TABLE "records_title_value" DROP CONSTRAINT "FK_846313cd8a383414fbbc7a972fc"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_a5f09c91bfe53121be839fd5754"`);
        await queryRunner.query(`ALTER TABLE "pages_sections" DROP CONSTRAINT "FK_e1c5792780a5472be4825966d94"`);
        await queryRunner.query(`ALTER TABLE "pages_sections_description_value" DROP CONSTRAINT "FK_1a83673d9038871d40167cee5eb"`);
        await queryRunner.query(`ALTER TABLE "pages_sections_title_value" DROP CONSTRAINT "FK_f528e26b260dd3549b3d12d351b"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock" DROP CONSTRAINT "FK_9ff9ce259ae047c9e72ca14b154"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_fields" DROP CONSTRAINT "FK_286592815ea93247dec6e525026"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field" DROP CONSTRAINT "FK_f929fe9c470a6478598aa51e2a1"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field" DROP CONSTRAINT "FK_e5dc88e85ea29c8192c9ea6fb7e"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records_field_value" DROP CONSTRAINT "FK_4f1a7deb7b7f84a540dfc7e6019"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_records" DROP CONSTRAINT "FK_ac05c90b7748d12564a17aa946f"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_section" DROP CONSTRAINT "FK_dacc6f7003e51056134cb17b68f"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_section_value" DROP CONSTRAINT "FK_59bb77f411f7c3be37ff26667ed"`);
        await queryRunner.query(`ALTER TABLE "pages_iblock_fields_label" DROP CONSTRAINT "FK_a979481317c46275274d317e314"`);
        await queryRunner.query(`ALTER TABLE "pages_seo_params" DROP CONSTRAINT "FK_d6d341a3d07869e14b4c55853a7"`);
        await queryRunner.query(`ALTER TABLE "pages_params" DROP CONSTRAINT "FK_d1470054f3bad349990679c249b"`);
        await queryRunner.query(`ALTER TABLE "pages_params_field" DROP CONSTRAINT "FK_4b3b4870b43caf984a5ff22139a"`);
        await queryRunner.query(`ALTER TABLE "pages_params_field" DROP CONSTRAINT "FK_1dad757c0e0f6e8e8c24c487058"`);
        await queryRunner.query(`ALTER TABLE "pages_params_field_value" DROP CONSTRAINT "FK_17cd61295a0eeaa3fd030861652"`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" DROP CONSTRAINT "FK_08220f7645a0e6e5e73ebf825bb"`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" DROP CONSTRAINT "FK_d2eb1a13366bb09677b8f8b9a94"`);
        await queryRunner.query(`ALTER TABLE "settings_menu_item" DROP CONSTRAINT "FK_bc7149e0b6c462ea0a78e25fcde"`);
        await queryRunner.query(`ALTER TABLE "pages-components" DROP CONSTRAINT "FK_e2cecde5138675709548651bdc3"`);
        await queryRunner.query(`ALTER TABLE "auth-confirm" DROP CONSTRAINT "FK_c1b9f162da24fa4cb098170b8cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_146347ac8247c1f560194c0046"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b3e0c5f255dc2934f4e08bf11"`);
        await queryRunner.query(`DROP TABLE "users_comments_like"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e60081aaa73c87282096ff7d02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b16cf6a8d2cd77c4e5c900e78"`);
        await queryRunner.query(`DROP TABLE "records_sections_pages_sections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03146727e4ec451f4d6569fe17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00c890d8787b39924577c17693"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_records_sections_pages_iblock_section"`);
        await queryRunner.query(`DROP TABLE "library_files"`);
        await queryRunner.query(`DROP TABLE "amo_custom_fields"`);
        await queryRunner.query(`DROP TABLE "callback"`);
        await queryRunner.query(`DROP TABLE "callback_field"`);
        await queryRunner.query(`DROP TABLE "callback_instances_value"`);
        await queryRunner.query(`DROP TABLE "callback_instances"`);
        await queryRunner.query(`DROP TABLE "reference_book"`);
        await queryRunner.query(`DROP TABLE "reference_book_attributes"`);
        await queryRunner.query(`DROP TABLE "reference_book_instances_value"`);
        await queryRunner.query(`DROP TABLE "reference_book_instances"`);
        await queryRunner.query(`DROP TABLE "settings-contacts"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "pages-comments"`);
        await queryRunner.query(`DROP TABLE "records"`);
        await queryRunner.query(`DROP TABLE "records_description"`);
        await queryRunner.query(`DROP TABLE "records_description_value"`);
        await queryRunner.query(`DROP TYPE "public"."records_description_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "records_seo"`);
        await queryRunner.query(`DROP TABLE "records_seo_params"`);
        await queryRunner.query(`DROP TYPE "public"."records_seo_params_fieldtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."records_seo_params_lang_enum"`);
        await queryRunner.query(`DROP TABLE "records_title"`);
        await queryRunner.query(`DROP TABLE "records_title_value"`);
        await queryRunner.query(`DROP TYPE "public"."records_title_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages"`);
        await queryRunner.query(`DROP TABLE "pages_sections"`);
        await queryRunner.query(`DROP TABLE "pages_sections_description_value"`);
        await queryRunner.query(`DROP TYPE "public"."pages_sections_description_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_sections_title_value"`);
        await queryRunner.query(`DROP TYPE "public"."pages_sections_title_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_iblock"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_fields"`);
        await queryRunner.query(`DROP TYPE "public"."pages_iblock_fields_type_enum"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_records_field"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_records_field_value"`);
        await queryRunner.query(`DROP TYPE "public"."pages_iblock_records_field_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_records"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_section"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_section_value"`);
        await queryRunner.query(`DROP TYPE "public"."pages_iblock_section_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_iblock_fields_label"`);
        await queryRunner.query(`DROP TYPE "public"."pages_iblock_fields_label_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_seo"`);
        await queryRunner.query(`DROP TABLE "pages_seo_params"`);
        await queryRunner.query(`DROP TYPE "public"."pages_seo_params_fieldtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pages_seo_params_lang_enum"`);
        await queryRunner.query(`DROP TABLE "pages_params"`);
        await queryRunner.query(`DROP TABLE "pages_params_field"`);
        await queryRunner.query(`DROP TABLE "pages_params_field_value"`);
        await queryRunner.query(`DROP TYPE "public"."pages_params_field_value_lang_enum"`);
        await queryRunner.query(`DROP TABLE "settings_menu_item"`);
        await queryRunner.query(`DROP TABLE "settings_menu"`);
        await queryRunner.query(`DROP TABLE "pages-components"`);
        await queryRunner.query(`DROP TABLE "auth-confirm"`);
    }

}
