version: '3.8'

services:
    backend:
        container_name: backendCMS
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/backend
            - /usr/src/backend/node_modules
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - 9229:9229
        command: npm run start:dev
        env_file:
            - .env
        networks:
            - webnet
        depends_on:
            - postgres
            - redis
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    redis:
        container_name: redisCMS
        image: redis:5
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        networks:
            - webnet
    postgres:
        container_name: postgresCMS
        image: postgres:12
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 4040:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    minio:
        container_name: minioCMS
        image: docker.io/bitnami/minio:latest
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
            MINIO_SERVER_URL: https://cloud.inter-sa.com:9000 # Укажите ваш домен
            MINIO_BROWSER_REDIRECT_URL: https://cloud.inter-sa.com:9001 # Укажите ваш домен
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - 'minio_data:/data'
            - './minio-certs:/certs'
        command: server --certs-dir /certs /data
        extra_hosts:
            - 'host.docker.internal:host-gateway'
networks:
    webnet:
volumes:
    pgdata:
    redis:
        driver: local
    minio_data:
        driver: local
